### ISSUE TITLE
How can i use TL-WN725N-V2 on Android X86?

### ISSUE THREAD

**Issue by Token713** [twd2/TL-WN725N-V2-Driver-for-Linux#2]
I have installed Android X86 OS on my PC,http://www.jide.com/remixos-for-pc#downloadNow
The Remix OS,I need to use my this USB Wifi adapter with my Computer,Please help me guys.

**Comment by twd2** [comment]
You may try to make and install, but this project is for BeagleBone actually and it just can run on my Ubuntu virtual machine.

Good luck!
Thanks.
